config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'users#show'
  resources :users, only: [:edit, :update, :show] do
    get 'account'
    resources :premia, shallow: true
  end
  resources :search
  resources :users, only: :show do
    resources :messages
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id
  belongs_to :parent, class_name: 'Message', foreign_key: :parent_id
  has_one :child, class_name: 'Message'

  validates_presence_of :body
end

app/models/premium.rb
class Premium < ActiveRecord::Base
  belongs_to :user
  validates :accept_terms_and_conditions, acceptance: true, allow_nil: false

  after_create :activate_premium

  def activate_premium
    self.user.update(premium: self)
  end

  def unsubscribe
    self.update(active: false)
    self.user.update(premium: nil)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :premia
  belongs_to :premium
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable

  validates :username,
            format: { with: /\A\w{3,20}\z/,
            message: 'username must be 3 to 20 characters long'}

  validates_length_of :bio, maximum: 500

  validates_numericality_of :height, only_integer: true
  validates_inclusion_of    :height,
                            in: 0..280,
                            message: "can only be between 0 and 280."

  validates_inclusion_of  :star_sign, in: %w(aries taurus gemini cancer leo virgo libra scorpio sagittarius capricorn aquarius pisces), allow_nil: true

  validates_inclusion_of  :dob,
                          in: Date.new(1900)..Time.now.years_ago(18).to_date,
                          message: 'You must be over 18 to register for this service'

  validates_inclusion_of :ethnicity,
                         in: %w(unspecified caucasian african asian hispanic other)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :dob, :gender]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def new
  end

  def create
    @message = Message.create(
                            sender_id: current_user.id,
                            receiver_id: params[:user_id],
                            body: message_params[:body]
                          )
    if @message.valid?
      redirect_to User.find(params[:user_id]), notice: 'Your message has been sent!'
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/premia_controller.rb
class PremiaController < ApplicationController
  def create
    @premium = current_user.premia.new(premium_params)
    if  @premium.save
      redirect_to user_account_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @premium = current_user.premia.find(params[:id])
    @premium.unsubscribe

    redirect_to user_account_path(current_user)
  end

  def new
    @user = current_user
    @premium = current_user.premia.new
  end

private
  def premium_params
    params.require(:premium).permit(:accept_terms_and_conditions)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  helper SearchHelper

  def index
    @matches = User.where(user_params).decorate
  end

  private

  def user_params
    params.require(:user).permit(:gender, :ethnicity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = (params[:id] ? User.find(params[:id]) : current_user).decorate
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to :root
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:smoker, :drinker, :dob, :ethnicity, :bio, :height, :star_sign)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def ethnicities
    [['Unspecified', nil], ['Caucasian', 'caucasian'], ['African', 'african'],
     ['Asian', 'asian'], ['Hispanic', 'hispanic'], ['Other', 'other']]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeGotSingles</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="nav">
    <div><h1>We Got Singles</h1></div>
    <div>
      <% if user_signed_in? %>
        <ul>
          <li><%= link_to 'Account', user_account_path(current_user) %></li>
          <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete  %></li>
        </ul>
      <% end %>
    </div>
  </div>

<%= yield %>
</body>
</html>

app/views/messages/new.html.erb
<%= form_for :message, url: user_messages_path do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% current_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='user_message'>
    <%= f.label :body, 'Message:' %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit 'Send Message' %>
<% end %>

app/views/premia/_premium.html.erb
<div>
  <%= render  ( current_user.premium ? 'premia/unsubscribe' : 'premia/subscribe' ) %>
</div>

app/views/premia/_subscribe.html.erb
<p> You currently have a Standar account. While this is great being a premium account holder has great advantages!! </p>
<%=link_to 'Subscribe', new_user_premium_path(current_user) %>

app/views/premia/_unsubscribe.html.erb
<p> You are a premium account holder since <%= current_user.premium.created_at %></p>

<%=link_to 'Unsubscribe', current_user.premium , method: :delete %>

app/views/premia/new.html.erb
<%= form_for [current_user, @premium]  do |f| %>
  <%= f.check_box :accept_terms_and_conditions %>
  <%= f.label :accept_terms_and_conditions %>
  <%= f.submit %>
<% end %>

app/views/search/index.html.erb
<% @matches.each do |match| %>
  <%= link_to(match.username, match) %>
  <%= match.dob %>
  <%= match.smoker %>
  <%= match.drinker %>
  <%= truncate(match.bio, length: 30, omission: '...(View profile for more)') %>
<% end %>

app/views/search/new.html.erb
<%= form_for :user, url: search_index_path, method: :get do |f| %>
  <h3> Searching for </h3>
  <h4>Gender:</h4>
  <%= f.select :gender, [['Male', true],['Female', false]] %>
  <h4>Ethnicity</h4>
  <%= f.select :ethnicity, render("users/shared/ethnicities") %>
  <br />
  <%= f.submit 'Search' %>
<% end %>

app/views/users/account.html.erb
<%= render 'premia/premium' %>

app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% current_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='user-dob'>
    <%= f.label :dob, 'Date of Birth' %>
    <%= f.date_field :dob, autofocus: true %>
  </div>
  <div class='user-height'>
    <%= f.label :height, 'Height (cm)' %>
    <%= f.number_field :height, min: 0, max: 280 %>
  </div>
  <div class='user-star-sign'>
    <%= f.label :star_sign, 'Star Sign' %>
    <%= f.select :star_sign, [
                              ['Aries', 'aries'],
                              ['Taurus', 'taurus'],
                              ['Gemini', 'gemini'],
                              ['Cancer', 'cancer'],
                              ['Leo', 'leo'],
                              ['Virgo', 'virgo'],
                              ['Libra', 'libra'],
                              ['Scorpio', 'scorpio'],
                              ['Sagittarius', 'sagittarius'],
                              ['Capricorn', 'capricorn'],
                              ['Aquarius', 'aquarius'],
                              ['Pisces', 'pisces']
                             ] %>
  </div>
  <div class='user-smokes'>
    <h3>Do you smoke?</h3>
    <%= f.radio_button :smoker, true %>
    <%= f.label :smoker_true, 'Yes' %>
    <%= f.radio_button :smoker, false %>
    <%= f.label :smoker_false, 'No' %>
  </div>
  <div class='user-drinks'>
    <h3>Do you drink?</h3>
    <%= f.radio_button :drinker, true %>
    <%= f.label :drinker_true, 'Yes' %>
    <%= f.radio_button :drinker, false %>
    <%= f.label :drinker_false, 'No' %>
  </div>
  <div class='user-ethnicity'>
    <h3>What's your ethnicity?</h3>
    <%= f.select :ethnicity, render('users/shared/ethnicities') %>
  </div>
  <div class='user-bio'>
    <h3>Personal Bio</h3>
    <%= f.text_area :bio %>
  </div>
  <br />
  <%= f.submit %>
<% end %>

app/views/users/shared/_ethnicities.html.erb
<%= options_for_select(
  [['Unspecified', 'unspecified'],
  ['Caucasian', 'caucasian'],
  ['African', 'african'],
  ['Asian', 'asian'],
  ['Hispanic', 'hispanic'],
  ['Other', 'other']]
) %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_star_sign.html.erb
<%= options_for_select(
[['Aries', 'arise'],
['Taurus', 'taurus'],
['Gemini', 'gemini'],
['Cancer', 'cancer'],
['Leo', 'leo'],
['Virgo', 'virgo'],
['Libra', 'libra'],
['Scorpio', 'scorpio'],
['Safittarius', 'sagittarius'],
['Capricorn', 'capricorn'],
['Aaquarius', 'aquarius'],
['Pisces', 'pisces']]) %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>
<ul>
  <li><%= @user.dob %></li>
  <li><%= @user.star_sign %></li>
  <li><%= @user.height %></li>
  <li><%= @user.gender %></li>
  <li><%= @user.smoker %></li>
  <li><%= @user.drinker %></li>
  <li><%= @user.height %></li>
  <li><%= @user.ethnicity %></li>
  <li><%= @user.bio %></li>
</ul>

<%= link_to 'search', new_search_path %>
<% unless @user.id == current_user.id %>
  <%= button_to 'Send Message', new_user_message_path(@user), method: :get %>
<% end %>